# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Back2base < Formula
  desc "Containerized Claude Code with curated MCP servers"
  homepage "https://back2base.net"
  version "0.70.1"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.70.1/back2base_darwin_amd64.tar.gz"
      sha256 "d4bfd262771f94309759ec31e5dd2344e7841dc7988d38cc826d865a96fd674c"

      define_method(:install) do
        bin.install "back2base"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.70.1/back2base_darwin_arm64.tar.gz"
      sha256 "d432ef0be948bfb986b8e18178c441aa4251551ccdf3c591cedc57e9bd919aaa"

      define_method(:install) do
        bin.install "back2base"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.70.1/back2base_linux_amd64.tar.gz"
      sha256 "88746438f475cb64a44c9602a377a5cd784b24ec204022592a511b99f9c20a84"
      define_method(:install) do
        bin.install "back2base"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.70.1/back2base_linux_arm64.tar.gz"
      sha256 "c8a2e2cb64880a8aca196b5f47e9cdd373d833a929e8193a41ca882189cae5e1"
      define_method(:install) do
        bin.install "back2base"
      end
    end
  end

  def post_install
    # Best-effort base-image pre-pull so the first `back2base run` doesn't
    # have to fetch ~500MB on a cold start. Then prune older base/compose
    # images so the user doesn't accumulate multi-GB drift across upgrades.
    # Both steps are skipped silently when docker isn't installed or
    # reachable — never fails the brew install.
    if which("docker")
      system "docker", "pull", "ramseymcgrath/back2base-base:latest"
      system "#{bin}/back2base", "prune", "--yes", "--quiet"
    end
  end

  def caveats
    <<~EOS
      back2base launches a containerized Claude Code session.

      First run pulls the base image (~500MB) and builds a thin local
      layer on top. To pre-fetch / pre-build ahead of time:

        docker pull ramseymcgrath/back2base-base:latest
        back2base build

      Sign in to enable cloud sync + memory MCP:

        back2base login
    EOS
  end

  test do
    system "#{bin}/back2base", "version"
  end
end
