# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Back2base < Formula
  desc "Containerized Claude Code with curated MCP servers"
  homepage "https://back2base.net"
  version "0.70.0"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.70.0/back2base_darwin_amd64.tar.gz"
      sha256 "2a5eb5d6261f7b49e597fbc81eebc80e25b7cb718dbc8aadcfc1c98d00829d19"

      define_method(:install) do
        bin.install "back2base"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.70.0/back2base_darwin_arm64.tar.gz"
      sha256 "87bb623ef7981f6c0ed9591f86dbb4c4555097c267c5e0b1b10628fcd19c9e28"

      define_method(:install) do
        bin.install "back2base"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.70.0/back2base_linux_amd64.tar.gz"
      sha256 "181786169c4d2ebfd8aec257ef12aa9057614d6c73ef5d1ab081ca6ca29ce9cf"
      define_method(:install) do
        bin.install "back2base"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/back2base/back2base-dist/releases/download/v0.70.0/back2base_linux_arm64.tar.gz"
      sha256 "e09090498178d695d3583cb74a9ac1e1ed6ffd33807fbf76ea963571451d4451"
      define_method(:install) do
        bin.install "back2base"
      end
    end
  end

  def post_install
    # Best-effort base-image pre-pull so the first `back2base run` doesn't
    # have to fetch ~500MB on a cold start. Then prune older base/compose
    # images so the user doesn't accumulate multi-GB drift across upgrades.
    # Both steps are skipped silently when docker isn't installed or
    # reachable — never fails the brew install.
    if which("docker")
      system "docker", "pull", "ramseymcgrath/back2base-base:latest"
      system "#{bin}/back2base", "prune", "--yes", "--quiet"
    end
  end

  def caveats
    <<~EOS
      back2base launches a containerized Claude Code session.

      First run pulls the base image (~500MB) and builds a thin local
      layer on top. To pre-fetch / pre-build ahead of time:

        docker pull ramseymcgrath/back2base-base:latest
        back2base build

      Sign in to enable cloud sync + memory MCP:

        back2base login
    EOS
  end

  test do
    system "#{bin}/back2base", "version"
  end
end
